### ISSUE TITLE
Bold/underline/strikethrough text styles

### ISSUE THREAD

**Issue by Ren60FHk** [hSaria/ChromaTerm#72]
Sorry for any inconvenience. Is it possible to add capability for the bold/underline/strikethrough text styles ?

**Comment by hSaria** [comment]
Sure. I'll find a clean way to integrate it into the existing `color` key without cluttering it.

**Comment by Ren60FHk** [comment]
> Sure. I'll find a clean way to integrate it into the existing `color` key without cluttering it.

Thank you )

**Comment by hSaria** [comment]
Aside from the following, anything else?
-   Blink
-   Bold
-   Italic
-   Striked
-   Underline

**Comment by Ren60FHk** [comment]
> Aside from the following, anything else?
> 
> * Blink
> * Bold
> * Italic
> * Striked
> * Underline

Nothing else for now )

**Comment by hSaria** [comment]
v0.4.2 published.
