### ISSUE TITLE
Scrolling up does not apply all Regexes

### ISSUE THREAD

**Issue by aaronols** [hSaria/ChromaTerm#75]
## Description
1. `ssh some-server | ct`
2. open log file with less on remote server
3. find some colorized lines
4. scroll down until the lines are out of view
5. scroll back up
6. Only some regexes are applied again

Scrolling down seems to always apply all regexes correctly while scrolling up fails to apply some of the more complicated ones..
It appears that the regexes applied when scrolling up are only the most simple ones.

## Environment
-   Terminal: zsh in tmux on wsltty
-   OS: [Ubuntu 18.04.3 LTS @ WSL @ Win10 1803 build 17134.1039]
-   ChromaTerm: [0.5.1]

## Configuration
This happens with the default configuration.
One pattern I observed not to be reapplied when scrolling up in the remote logs is the date Pattern in the format YYYY-MM-DD.
The time pattern was correctly reapplied when scrolling up though.

**Comment by hSaria** [comment]
Fixed in 6c1a79f8c3442386404d9d6309a97be96c2d7524. v0.5.2 will be published soon (tomorrow probably).

**Comment by aaronols** [comment]
Thank you very much for fixing this too. It works marvellously 👍

**Comment by hSaria** [comment]
And thank you for raising the issue. I greatly appreciate it.
