### ISSUE TITLE
Certain regex pattern gives strange output

### ISSUE THREAD

**Issue by Enf0** [hSaria/ChromaTerm#81]
The regex pattern in question:
`^([^$#(]+)(\$|#|\([^)]+\)#)`

Expected output:
`xxUser123@server-001:~$
`
Actual output:
`0;xxUser123@server-001: ~xxUser123@server-001:~$ `

Any idea why this is happening? Is there something wrong with the regex, or could it be a bug with Chromaterm?

**Comment by hSaria** [comment]
I cannot seam to reproduce this. Which version of ChromaTerm are you running?

**Comment by Enf0** [comment]
Very strange. Might be something wrong with my shell?
![image](https://user-images.githubusercontent.com/825808/73916925-aeb05800-48be-11ea-9985-5cfd64b724e0.png)

Chromaterm 0.5.7.

**Comment by hSaria** [comment]
I would imagine this is matching some value in the PS1 of the server. Would you mind running
```
ssh server | tee pre.txt | ct | tee post.txt
```
and attaching `pre.txt` as well as `post.txt` (feel free to remove anything sensitive in the files).

**Comment by Enf0** [comment]
[pre.txt](https://github.com/hSaria/ChromaTerm/files/4165091/pre.txt)
[post.txt](https://github.com/hSaria/ChromaTerm/files/4165092/post.txt)

**Comment by hSaria** [comment]
CT was not ignoring Operating System Command (OSC) codes, which include setting the title. This has been fixed now and will be published in v0.5.8 soon. Thanks a lot for your help with this :)
