### ISSUE TITLE
ct: command not found

### ISSUE THREAD

**Issue by globe2018** [hSaria/ChromaTerm#85]
how to install and use  ?

## Description
after pip3 install chromaterm , 
then excute 「echo "Jul 14 12:28:19  Message from 1.2.3.4: Completed successfully" | ct 」

error message :
command not found: ct

## Environment
environment : Ubuntu 18.04

**Comment by hSaria** [comment]
The explanation is in https://github.com/hSaria/ChromaTerm/issues/77#issuecomment-550017792, but to summarize:

`ct` should be in `$HOME/.local/bin`, so add this this to your `.bash_profile` or `.bashrc` (or the config file of the shell you use):
```
PATH="$HOME/.local/bin:$PATH"
```

This would affect not just ChromaTerm, but any Python-based command program installed via pip.
