### ISSUE TITLE
Broken display of top and top

### ISSUE THREAD

**Issue by nzkller** [hSaria/ChromaTerm#87]
## Environment
* OS: macOS Catalina Version 10.15.3
* Terminal: iTerm2 Build 3.3.10beta4
* ChromaTerm: 0.6.1

You canse in the images below, the output for top and top are broken and unreadable.

![Screen Shot 2020-05-17 at 1 13 29 AM](https://user-images.githubusercontent.com/18606875/82136439-2e15c780-97dc-11ea-8b6b-38fbe8c7f2de.png)

![Screen Shot 2020-05-17 at 1 18 25 AM](https://user-images.githubusercontent.com/18606875/82136461-543b6780-97dc-11ea-9077-abc05984a62e.png)

The configuration file in attached as well.

[chromaterm.txt](https://github.com/hSaria/ChromaTerm/files/4639689/chromaterm.txt)

Maybe this is normal due to my regex, but I'm not certain.

Thank you in advance and best regards,

CD

**Comment by hSaria** [comment]
Thanks for the submission! This has been fixed and will be published in v0.6.2 soon.
