### ISSUE TITLE
psutil not supported in Cygwin

### ISSUE THREAD

**Issue by vikdean** [hSaria/ChromaTerm#90]
PSUtils not supported in Cygwin
```
[~]$ pip3 install chromaterm
Collecting chromaterm
  Using cached chromaterm-0.6.3-py3-none-any.whl (17 kB)
Collecting psutil; sys_platform != "win32"
  Using cached psutil-5.7.2.tar.gz (460 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ev3folk5/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ev3folk5/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i0bk4d6b
         cwd: /tmp/pip-install-ev3folk5/psutil/
    Complete output (1 lines):
    platform cygwin is not supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Is there a way around this?

**Comment by hSaria** [comment]
Can you elaborate on what you're attempting to do? From what I can tell, you have Python installed through Cygwin, likely for the sake of compatibility.

I can't do anything about PSUtil's support of Cygwin, or lack thereof. However, I would highly recommend using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10); not only does this work very well for ChromaTerm, but this will give a consistent experience when running other Linux binaries.

**Comment by vikdean** [comment]
Unfortunately I can only use Cygwin; my question really is, if there is a way not to use psutil or use something else instead.

**Comment by hSaria** [comment]
My main concern is that ChromaTerm's command line script (`ct`) will not even work correctly (I've tried offering support for PowerShell and CMD, but it didn't work as you might expect, namely when piping the output of a program).

You've got a couple of options to try:
* Ignore the dependencies when installing through pip: 
```
pip3 install --no-deps chromaterm
```

* Clone the repo, comment out the `psutil` requirement, then install it locally:
```
# Clone on a specific tag (current latest version)
git clone -b 0.6.3 https://github.com/hSaria/ChromaTerm.git

# Remove the line with 'psutil' (I used 'sed' here, but you can do that manually if you'd like)
sed -i '' '/psutil/d' ChromaTerm/setup.py

# Install ChromaTerm from a local path
pip3 install -e ChromaTerm/
```

**Comment by vikdean** [comment]
Hmm, its seems to be working, but I'll have to test it further. Thanks for the help.

**Comment by hSaria** [comment]
Glad to hear it.
