### ISSUE TITLE
ChromaTerm installation error on macOS BigSur

### ISSUE THREAD

**Issue by ciscohack** [hSaria/ChromaTerm#92]
## Environment
* OS:macOS Big Sur 11.4 
* Terminal:Iterm2 Nightly
* ChromaTerm: 

## Description
Hi Team,

I am trying to install Chromaterm and getting following error on my macOS BigSur 11.4 while running pip3 install. Please help me to fix this problem and i request you to please add more keywords for color highlight

log:--

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', IsADirectoryError(21, 'Is a directory'))': /simple/chromaterm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', IsADirectoryError(21, 'Is a directory'))': /simple/chromaterm/
[pip3 install chromaterm-error.txt](https://github.com/hSaria/ChromaTerm/files/6720452/pip3.install.chromaterm-error.txt)

**Comment by hSaria** [comment]
This seems to be a client-specific issue. Some people in https://github.com/pypa/pip/issues/7424 experienced something similar, some of whom mention that restarting their terminal and retrying fixed it.

I'm not quite sure what's the cause of this issue, but I think this is an error coming from `pip`; try install a different package to see if you're getting the same error.

> please add more keywords for color highlight

ChromaTerm's highlight rules are customizable, so you can add more to your configuration file `~/.chromaterm.yml` (see [`readme`](https://github.com/hSaria/ChromaTerm#highlight-rules) for more details on that.

**Comment by ciscohack** [comment]
i restarted system even that not solved the problem. Could you please help me to know any alternate way to install it

**Comment by hSaria** [comment]
You can install locally like so:
```
git clone https://github.com/hSaria/ChromaTerm.git
cd ChromaTerm
python3 setup.py install
```
The above will install the latest **development** version. If you'd like to install a specific version, replace the clone command with this, then follow the same steps. 
```
git clone --branch 0.7.2 https://github.com/hSaria/ChromaTerm.git
```

**Comment by ciscohack** [comment]
Thanks my friend for quick help but still have error.


Installed /usr/local/lib/python3.9/site-packages/chromaterm-0.7.3.dev0-py3.9.egg
Processing dependencies for chromaterm==0.7.3.dev0
Searching for PyYAML
Reading https://pypi.org/simple/PyYAML/
Download error on https://pypi.org/simple/PyYAML/: [Errno 21] Is a directory: '/Users/praverai/sslkeyfile' -- Some packages may not be found!
Couldn't find index page for 'PyYAML' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 21] Is a directory: '/Users/praverai/sslkeyfile' -- Some packages may not be found!
No local packages or working download links found for PyYAML
error: Could not find suitable distribution for Requirement.parse('PyYAML')

**Comment by hSaria** [comment]
Can you run `pip3 -V`?

**Comment by ciscohack** [comment]
> Can you run `pip3 -V`?

 ChromaTerm on   master  pip -V                                                                                                                                                                      
pip 21.1.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by ciscohack** [comment]
if i run this command 
git clone --branch 0.7.2 https://github.com/hSaria/ChromaTerm.git

then if i run following command
pip3 install PyYAML psutil
 
will this install ct and it's dependency completely

**Comment by hSaria** [comment]
You have to install the dependencies first.

**Comment by ciscohack** [comment]
you mean first i run this command pip3 install PyYAML psutil then git clone --branch 0.7.2 https://github.com/hSaria/ChromaTerm.git  by doing this do i get complete setup ready

**Comment by hSaria** [comment]
Yes. But again, this seems like a bigger issue with `pip` or `PyPI`. I think this is affecting more than just ChromaTerm on your system.

**Comment by ciscohack** [comment]
yes you are correct pip is broken. i am not able to install any package. what should i do

**Comment by hSaria** [comment]
Looking at the logs you provided, I'm guessing you're using HomeBrew to install Python. I also have Python installed from HomeBrew on macOS Big Sur, so that shouldn't be the problem, but maybe try to reinstall it:
```
brew reinstall python@3.9
```

**Comment by ciscohack** [comment]
i did just now had same thought no luck

**Comment by hSaria** [comment]
Saw `/Users/praverai/sslkeyfile` in the logs; are you doing any network inspection that's modifying the data?

**Comment by ciscohack** [comment]
yes just noticed and fixed.thanks a lot

**Comment by ciscohack** [comment]
between my friend you are awesome. now i just have to learn to make more keyword for highlight

**Comment by ciscohack** [comment]
This file ~/.chromaterm.yml will be auto created or i need to create. if you don't mind may i have your yml file as i know you already have some customisation and i will more idea from your file to extend it for my use case

**Comment by hSaria** [comment]
When you launch ChromaTerm, it will check to see if one exists. If not, it'll create one. Just run `echo | ct` and one will be created.

It's really easy to add rules. Just edit `~/chromaterm.yml` and add one at the bottom. You do have to know a bit of RegEx. There are a lot of tutorials online; [Python](https://docs.python.org/3/library/re.html#regular-expression-syntax) has a great one.

Here's a rule to highlight your username:
```
- description: My username
  regex: \bpraverai\b
  color: bold f#28AD54
```

I'm using the boundary (`\b`) to make sure that the word is only highlighted if it's on its own (i.e. it's not in the middle of another word, like `aaapraveraiaaa`).

Don't try to learn all of RegEx in one go. It's too much 😄. Instead, search only for what you're trying to do online and learn that way.

**Comment by ciscohack** [comment]
Thanks my friend

**Comment by ciscohack** [comment]
@hSaria I am using Chromaterm on macOS default terminal for device ssh and some of keywords which is not in my config but i don't know why i have blue selection layout showing most of lines and how can i fix it.

Second  in color scheme what f and b prefix defination means (f#28AD54) and (b#28AD54)



![image](https://user-images.githubusercontent.com/11479557/123546619-fae18e00-d77a-11eb-8171-d5c38853e549.png)

**Comment by ciscohack** [comment]
Look like a bug for macOS native terminal now whole screen turn like this but i have no such issue with iterm2 terminal. any idea how to fix it

![image](https://user-images.githubusercontent.com/11479557/123546731-7b07f380-d77b-11eb-95c0-49cb2f9051e5.png)

**Comment by hSaria** [comment]
I use macOS Terminal and haven't had something like this. Can you attach your configuration file? Namely, any custom rules you might've added.

**Comment by ciscohack** [comment]
> I use macOS Terminal and haven't had something like this. Can you attach your configuration file? Namely, any custom rules you might've added.

Bu this issue only happening with me on native terminal not all.
[chromaterm.yml.zip](https://github.com/hSaria/ChromaTerm/files/6721787/chromaterm.yml.zip)

**Comment by hSaria** [comment]
> Bu this issue only happening with me on native terminal not all
The ANSI standard is pretty loose in some regards, so terminal emulators will often account for errors in code and display what they think is correct, while others are more literal and do exactly what they're told.

I see you've added quite a few rules. Looking at the descriptions, I think those are from [FeralPacket](https://feralpacket.org/?p=817), which are meant from SecureCRT that uses `ECMAScript` as their RegEx engine, [I think](https://forums.vandyke.com/showthread.php?t=13089). ChromaTerm uses Python's built-in [`re`](https://docs.python.org/3/library/re.html). There are differences in the syntax of special kinds of functions which I suspect is causing inaccurate mismatching.

Seeing that you've got a lot of rules, you could one of the following to help solve your issue:
* Run `ssh your-device | tee -a pre.txt | ct | tee -a post.txt`, then close the SSH session once you get the issue and attach `pre.txt` and `post.txt` here.
* Disable half of the rules you added (comment the rule with `#`) and verify if the issue was fixed. If it is, then enable half of the ones you disabled. Keep doing this until you find which one is the rule is incorrectly matching.

**Comment by ciscohack** [comment]
Yes some of rules i used of FeralPacket. i am not very good with regex :) But need these to highlight for speed up my work. I am attaching the requested log. I know you also in same domain and i love if you could share your config.

One more request or i don't know if this exist. suppose if i have log file and i want to highlight keyword while reading if use less to open file and pipe that file with CT then it highlight the text but pager then not work. it render all file all along. is there way to pipe CT but pager still work.

[post.txt](https://github.com/hSaria/ChromaTerm/files/6721918/post.txt)
[pre.txt](https://github.com/hSaria/ChromaTerm/files/6721919/pre.txt)

**Comment by hSaria** [comment]
My file is quite simple. It uses the default config and some rules from [`contrib/rules`](https://github.com/hSaria/ChromaTerm/tree/master/contrib/rules). Here's my [config file](https://github.com/hSaria/ChromaTerm/files/6721935/chromaterm.yml.txt).

Thanks for the log files. I'll take a look.

You can let ChromaTerm spawn your program, like `ct less file.txt`. From `readme`:
> Some programs behave differently when piped, like `less`. In that case, `ct` can hide the pipe by spawning your program. You just have to prefix the command with `ct`, like `ct less file.txt`.

**Comment by hSaria** [comment]
Can you reattach the file but with `/usr/bin/ssh your-device | tee -a pre.txt | ct | tee -a post.txt`. I forgot that you're already highlighting the default `ssh` command.

**Comment by ciscohack** [comment]
> Can you reattach the file but with `/usr/bin/ssh your-device | tee -a pre.txt | ct | tee -a post.txt`. I forgot that you're already highlighting the default `ssh` command.

Sure np i will do it again meanwhile could you please tell me about this request "One more request or i don't know if this exist. suppose if i have log file and i want to highlight keyword while reading if use less to open file and pipe that file with CT then it highlight the text but pager then not work. it render all file all along. is there way to pipe CT but pager still work."

**Comment by hSaria** [comment]
I already did :). I'll paste it again:

You can let ChromaTerm spawn your program, like `ct less file.txt`. From `readme`:
> Some programs behave differently when piped, like `less`. In that case, `ct` can hide the pipe by spawning your program. You just have to prefix the command with `ct`, like `ct less file.txt`.

**Comment by ciscohack** [comment]
[post.txt](https://github.com/hSaria/ChromaTerm/files/6721981/post.txt)
[pre.txt](https://github.com/hSaria/ChromaTerm/files/6721982/pre.txt)

Please find the attachment as requested. Thanks for looking into it and please do answer to my other query also

**Comment by ciscohack** [comment]
> My file is quite simple. It uses the default config and some rules from [`contrib/rules`](https://github.com/hSaria/ChromaTerm/tree/master/contrib/rules). Here's my [config file](https://github.com/hSaria/ChromaTerm/files/6721935/chromaterm.yml.txt).
> 
> Thanks for the log files. I'll take a look.
> 
> You can let ChromaTerm spawn your program, like `ct less file.txt`. From `readme`:
> 
> > Some programs behave differently when piped, like `less`. In that case, `ct` can hide the pipe by spawning your program. You just have to prefix the command with `ct`, like `ct less file.txt`.

Thanks will try that. you are awesome.

**Comment by hSaria** [comment]
I ran your configuration file against the data (i.e. `cat pre.txt | ct --config chromaterm.yml`) and highlighting looks to be working just fine.

<img width="578" alt="Screenshot 2021-06-27 at 18 07 03" src="https://user-images.githubusercontent.com/34197532/123553368-b3570400-d772-11eb-80f3-8bbf7e636adc.png">

Are you using a special Terminal profile? Try using the default profile. Press `⌘ ,` and under the `Profiles` tab, double-click the thumbnail of the `Basic` profile, then run `ssh some-device` as usual and see if it displays correctly.

**Comment by ciscohack** [comment]
> I ran your configuration file against the data (i.e. `cat pre.txt | ct --config chromaterm.yml`) and highlighting looks to be working just fine.
> 
> <img alt="Screenshot 2021-06-27 at 18 07 03" width="578" src="https://user-images.githubusercontent.com/34197532/123553368-b3570400-d772-11eb-80f3-8bbf7e636adc.png">
> 
> Are you using a special Terminal profile? Try using the default profile. Press `⌘ ,` and under the `Profiles` tab, double-click the thumbnail of the `Basic` profile, then run `ssh some-device` as usual and see if it displays correctly.

Yes i am using spacedust theme in native terminal. leave it brother then. i now installed hyperterm and work flawless. I am still curious to know your config to try if that is not having sensitive data and secret. Thanks once again for your help

**Comment by hSaria** [comment]
Glad I could help. I already attached my config in a previous comment.

**Comment by ciscohack** [comment]
Thanks once again
