### ISSUE TITLE
Prompt isn't visible immediately when using `tmux`

### ISSUE THREAD

**Issue by hSaria** [hSaria/ChromaTerm#97]
### ChromaTerm version

v0.9.2

### Terminal

iTerm2

### What's happening?

_Originally posted by @ciscohack in https://github.com/hSaria/ChromaTerm/issues/96#issuecomment-1012800894_

When using `tmux`, the prompt takes longer to become visible again. Below is a demonstration. When using `ct zsh`, it is responsive, but when using `ct tmux`, the prompt takes a bit of time to respond.

https://user-images.githubusercontent.com/34197532/149534554-39f326f3-b807-42ed-b4fa-29cea43e9099.mov

This was tested with a default configuration file.

**Comment by hSaria** [comment]
@ciscohack, can you test the fix by running the code below
```shell
patch /usr/local/lib/python3.9/site-packages/chromaterm/__main__.py << EOF
45,47c45,48
< # The start of a control string
< SPLIT_CONTROL_STRINGS = (b'\x1b\x50', b'\x1b\x58', b'\x1b\x5d', b'\x1b\x5e',
<                          b'\x1b\x5f')
---
> # Control strings that have arbitrary lengths
> ANSI_CONTROL_STRINGS_START = (b'\x1b\x50', b'\x1b\x58', b'\x1b\x5d',
>                               b'\x1b\x5e', b'\x1b\x5f')
> ANSI_CONTROL_STRINGS_END = (b'\x07', b'\x1b\x5c')
322,323c323,325
<             # Separator is an incomplete control strings; wait for the rest
<             if data_read and separator.startswith(SPLIT_CONTROL_STRINGS):
---
>             # Separator is an incomplete control string; wait for the rest
>             if data_read and separator.startswith(ANSI_CONTROL_STRINGS_START) \
>                     and not separator.endswith(ANSI_CONTROL_STRINGS_END):
EOF
```

This issue was related to `tmux`'s use of a special ANSI sequence called `Device Control String`. When it appeared at the very end of the data, `ct` was waiting to ensure it was a complete sequence, but it did so without checking if it was already complete or not. The patch above fixes that.

**Comment by hSaria** [comment]
ChromaTerm v0.9.3 released with a fix for this issue.

**Comment by ciscohack** [comment]
@hSaria Sorry for delay response. I am travelling so not able to test But issue is not about prompt delay.. issue is about latency while reading logs and search. issue was more adverse on iterm2 app but less on hyperterm.

**Comment by ciscohack** [comment]
@hSaria I just updated my CT and now everything working flawless. Thanks a lot. you can close the ticket now.

Please consider my suggestion or call it request in your future update of this lovely App.

"Can you include more default regex for basic captures for network.. like all type of Interfaces/ Routing protocol/ ACL and some basic Syslog.. Just to give default flavour of regex install and use then people add their own rule later. just a request upto you."

**Comment by hSaria** [comment]
Take a look at the contrib directort of this project. They’re not included in the default config because not many people require them.

**Comment by ciscohack** [comment]
Sure! Thanks
