### ISSUE TITLE
CT rendering issue with Kitty terminal

### ISSUE THREAD

**Issue by ciscohack** [hSaria/ChromaTerm#98]
### ChromaTerm version

v0.10.1

### Terminal

Kitty terminal

### What's happening?

Hello Expert,

I am trying to run CT in kitty terminal i used following configuration in kitty.conf file "shell /usr/local/bin/ct zsh --login" after putting this config terminal wide CT starts but since i use terminal window in tmux rendering got messed up. Can you please help to fix it. See below screenshot it's rendering wrong format

<img width="2042" alt="image" src="https://user-images.githubusercontent.com/11479557/159220389-edef30e3-dc68-40a5-8552-e0144c94625c.png">

ideally it should show like this 

<img width="1803" alt="image" src="https://user-images.githubusercontent.com/11479557/159220695-1be36c10-b9d6-401e-8312-ccead5f1d685.png">

**Comment by hSaria** [comment]
I configured `shell /usr/local/bin/ct zsh --login` in `.config/kitty/kitty.conf`, reloaded the preferences, and highlighted is working just fine. I also tested tmux and it still works as expected.

Can you please clarify exactly what you're doing that's causing this issue?

**Comment by ciscohack** [comment]
@hSaria Thanks for the response. As you saw in my older post comment i did very same config and but having issue like screenshot. Okay to reproduce this issue you might need first to install this z shell with tmux integration enabled then trying this config  "shell /usr/local/bin/ct zsh --login"  you will see the issue.

https://github.com/romkatv/zsh4humans

<img width="1846" alt="image" src="https://user-images.githubusercontent.com/11479557/159277996-7b4c2148-05bd-4f6b-a400-a4ef769ac342.png">

**Comment by ciscohack** [comment]
Sure @hSaria  Thanks for your time.  

this is my config in zshrc  of zsh4human shell. 

zstyle ':z4h:' start-tmux       command tmux -u new -A -D -t z4h

**Comment by hSaria** [comment]
I already have `zstyle ':z4h:' start-tmux       command tmux -u new -A -D -t z4h` as I enabled the `tmux` integration. I still cannot reproduce the issue.

**Comment by ciscohack** [comment]
@hSaria can you share your kitty.conf . let me try that .. don't know what is causing this problem for me then

**Comment by hSaria** [comment]
It's literally a single line containing the shell.
```
shell /usr/local/bin/ct zsh --login
```

**Comment by ciscohack** [comment]
@hSaria  it's not about single line my friend this above command i myself figure out but it's breaking in my system due to some reason and i figure out the reason now. You just add this config in your kitty.conf "macos_show_window_title_in none" and this will break CT in kitty. if you could fix it then it would good help. Thanks

**Comment by ciscohack** [comment]
@hSaria You can close the thread...Thanks for your time and help

**Comment by hSaria** [comment]
I tried `macos_show_window_title_in none` but I still cannot reproduce it. Please attach your `kitty.conf`.

**Comment by ciscohack** [comment]
@hSaria please close the thread i have fixed the issue. Thanks

**Comment by hSaria** [comment]
Ideally, you shouldn't see these codes unless they were being shown on purpose (_i.e._ not properly escaped) which means you would've seen them with or without `ct`. However, if they're only seen while `ct` is running, then there's something to fix.

**Comment by ciscohack** [comment]
@hSaria  Sorry for bothering you but need your help. tried all options on my new laptop but it's failing. Actually, I installed the Alacrity terminal and set system-wide CT  this is my config but it not working, and tried others but failed. if you could help

shell:
  program: /usr/local/bin/ct
  args:
    - zsh --login

**Comment by ciscohack** [comment]
@hSaria  please ignore I have fixed it by this config snippet

shell:
 program: /usr/local/bin/ct
 args:
   - /bin/zsh
   - --login
